name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: bbbanalytics
        postgresql user: postgres 
        postgresql password: postgres
    - run: npm install
    - run: npm run build --if-present
    - run: npm run test
      env:
        CI: true
        JWT_SECURITY_SALT: fakesessionsecret
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/bbbanalytics
        HOSTNAME: localhost
